### ISSUE TITLE
'role' is not of type 'object' - 'messages.13'

### ISSUE THREAD

**Issue by Captain-Bacon** [JLX0/MetaLLM-GPT#2]
When running the file with the following prompt (I use it as a nice little test), I get an error.

python mg.py -o "create a version of the lemonade stand game including any assets" -f "lemonadestand.py" -k "sk-the-rest-of-the-key"

    raise self.handle_error_response(
openai.error.InvalidRequestError: 'role' is not of type 'object' - 'messages.13'

**Comment by JLX0** [comment]
Thanks for letting me know! I just fixed the bug. It was caused by a missing [] in line 124 of the file prompt.py. In addition, for this prompt, it is suggested to set -p True (with a virtual environment), or manually specify which packages you want to use with -e 1.package_1 2. package_2 .... Otherwise the app assumes you do not want to use any packages beyond the built-in python modules.
