### ISSUE TITLE
Repository restructuring proposal

### ISSUE THREAD

**Issue by Juno-T** [JLX0/MetaLLM-GPT#3]
Hi, this is Juno.

First of all, I find it very interesting and has potential to be a novel way of kick-starting any coding project or even semi-automated project development. I'm thinking of improving the prompts but at the current state, I feel like the repo is not very well-structured which is quite hard to do so. So before I do any improvement, I want to propose restructuring this repo. This is what I imagine it could be.

# Proposal
The goal is to have a clean loop like this:
``` python
max_iteration = 10
history = []
old_code_blob = CodeBlob()
while max_iteration:
    prompt_mode, prompt = prompter.prompt(old_code_blob)
    response = openai.ChatCompletion.create(model, prompt)
    code_str = parse_code(response)
    new_code_blob = executor(code_str)
    history.append(PromptStep(old_code_blob, prompt, prompt_mode, response, new_code_blob))
    old_code_blob = new_code_blob
    max_iteration -= 1
```
It will be clearer after finish reading the rest.

### Common code execution object
The core element of the project is about code execution. What would be great is to have some common object representing the entire data related to the code execution.

``` python
class CodeBlob:
    code: str
    compiled_code: str
    execution_result: str
    exception: str
    traceback: str
    execution_time: float
    environment: ??
    ...
```

### PromptStep object
The second most important data are those involving chatGPT API calling.
``` python
class PromptStep:
    code_old: Union[None, CodeBlob]
    prompt_mode: Literal['create', 'debug', etc]
    prompt: str
    raw_response: str
    code_new: CodeBlob
```
These two objects should cover most of the usecase and establish a common protocol between modules.
Additionally, the design of these two objects is very close to RL -- if you look at the `PromptStep`, it is basicaly a RL's timestep tuple `(s_tm1, a_tm1, s_t)` where states are `CodeBlob`s and actions are the prompts.

## Modules and Functions
With these two objects, designing the modules becomes trivial.

### Code Parsing function
Basically turn the API's response into an executable str of code.
``` python
def parse_code(raw_response) -> str:
    pass
```

### Code Executor module
As the name suggest, upon calling execute function given the parsed code str, it will return the CodeBlob object.
Using the RL analogy, this is corresponding to the environment.
``` python
class CodeExectutor:
   def __init__(self):
        pass

    def  execute(self, code_str: str) -> CodeBlob:
        pass
```

### Prompting Module
This module responsible for generating prompt given the execution result of the code (`CodeBlob`).
Here I think a better design of managing prompt template is to put them into a file, maybe txt or json or yaml.
Again, same analog, prompting module corresponding to "policy" in RL. With this abstraction, the developer (or extreme users) can create new prompt templates to improve their usecase.

``` python
class Prompter:
   def __init__(self, config_file):
        self.load_config(config_file)
        ...

    def  prompt(self, code_blob: CodeBlob) -> Tuple(str, str):
        # code_blob can even be code_blobs (list of execution history)
        if code_blob.exception is not None:
            mode = "debug"
        return mode, self.from_template(code_blob, mode)
        ...

    def from_template(code_blob: CodeBlob, mode="create) -> str:
        pass
```

### Code Generator module
This is quite similar to the original `MetaLLM_GPT` class. However, it will look a lot cleaner and more modular for easy customization (e.g. with new prompter that internally call chatGPT to construct the prompts, or new code executor for different languages etc.)

The original `MetaLLM_GPT` will become an instance of `CodeGenerator` with a specific prompter and a specific code executor.
``` python
class CodeGenerator:
    def __init__(self, prompter: Prompter, executor: CodeExecutor, model, environment, etc.):
        self.prompter = prompter
        self.execture = executor
        self.history = []

    def run(self, max_iteration=10):
        old_code_blob = CodeBlob()
        while max_iteration:
            prompt_mode, prompt = self.prompter.prompt(old_code_blob)
            response = openai.ChatCompletion.create(model, prompt)
            code_str = parse_code(response)
            new_code_blob = self.executor(code_str)
            self.history.append(PromptStep(old_code_blob, prompt, prompt_mode, response, new_code_blob))
            old_code_blob = new_code_blob
            max_iteration -= 1
        ...
```

The `CodeGenerator` is arguably unnecessary since it is just the while loop. Developers can modify this loop to fit their needs or even implement it with other code-repairing technique like the [_repair tree_](https://arxiv.org/abs//2306.09896).

### Where are the files?
If I understand correctly, there is no need to write code into a file during the iteration loop. So holding the code_str inside the memory should be okay. We can let the user write out the code into a file later as needed.
However, if it is necesary to write into a file(s), e.g. in the future where it can generate a repo, in that case we can write out the files inside the `CodeExectutor` module during the code execution, which is relatively easy to do.

To debug, we can just look at the history inside the `CodeGenerator`.

### Too early for abstraction?
It is debatable but in my opinion, it has already reached the size where abstraction is worth to do.

### Backward compatibility?
This restructuring will break backward compatibility. However, just a few line of code changes in the colab notebook should be enough to fix the problem. Without restructuring, any major improvement would break the backward compatibility anyway.

# Footer
- We can reuse most of the codes. But they will be reorganized heavily.
- With this new structure, if I want to improve the prompt, I can easily edit the `prompt_config` or edit the `Prompter` module without breaking other modules.
- Documentation will be way more easy.
- This is just a proposal which should be discussed before start implementing. So, please comment your thoughts!

**Comment by JLX0** [comment]
Dear Juno

Thank you very much for your suggestions. You offered several valuable ways to change the code.

1. An object that represents the state of the code (e.g., CodeBlob) is possible. It would be convenient to have an object like this to be read. In this case, I think I will add such an object soon. However, for this object to be written, it is not very convenient. Such an object is possible, but it will make the files code_management.py and mg_core.py more complicated, which are already very complicated. For example:
- functions meta_python.read(), meta_python.write(), and meta_python.compile() would have to return more arguments.
- functions in meta_python will have more arguments, which would make the most complicated parts in mg_core.py and code_management.py even more complicated. For example, it will make line 113 to line 120 in mg_core.py even longer.

- One of the main purposes of this code, besides the application itself, is to create a metaprogramming module for Python codes. So I would like to make mg_core.py and code_management.py in the main branch to be as simple as possible. In this way, the meta-programming features in this application can be easier to be used for other research/applications. 

- If you intend to use it in an RL environment, in some cases, it might be better to create an object that is writable for the state of the code. In this case, I suggest you create an additional branch. If you need any assistance, let me know.

- Nonetheless, I will try if I can make a readable and writable object like this without overcomplicating mg_core.py or code_managment.py

2. To create an object for the action in an RL setting, I think generally you can directly copy some of the arguments listed in mg.py as the class/instance variable. 

3. The suggestion about saving the prompt/settings into a file is very good. I am also considering this feature. Because sometimes the settings can be too long to be comfortably typed into the Terminal or the Google Colab input boxes

4. About the code generator module: It is not recommended to simplify the class MetaLLM_GPT into the class CodeGenerator. Because:

- The application itself, aka, the meta-program, is subject to exceptions. For example, it can happen due to occasional internet disconnection or bad responses from the LLM (e.g., the generated code is too short, the code takes too long to run or the code cannot finish at all (which happens quite often), the code cannot be retrieved by GPT_turbo.extract_code_from_GPT_turbo() in inquiry.py ). Although it might be possible to configure the application to reach a relatively decent success rate, it is almost impossible to achieve a 100% success rate. Also, such a design would make the code repo generalize poorly. Because a design that is suitable for GPT might "overfit" GPT and is less successful for other LLMs.

- It can be very difficult to achieve all types of meta-programming features with just the following two lines:

````
            code_str = parse_code(response)
            new_code_blob = self.executor(code_str)
````
- For example, how to achieve the termination of the execution of the code if the code takes too long to finish? I tried to convert overtime_kill() in code_management.py into a decorator but it seems that Python is unable to accept such a decorator. Also, the termination of a target program by a meta program using multiprocessing requires a shared dictionary from Manager() to store the variables, otherwise, the meta program is unable to access the values stored in the target program. I do not think the current version of Python is robust enough to handle metaprogramming very well. For example, from the traceback of the target program, you could see that the traceback is from "code_to_be_compiled", which is misleading. I still do not know how to solve this issue yet. Therefore, it can be very difficult to create an object as simple as CodeGenerator for this application

- I might move the function MetaLLM-GPT.inquiry_GPT into another class, which could possibly make the code simpler.

5. I store the generated code into a file in each iteration because the meta program itself might not be able to finish due to some reasons, such as an internet disconnection or an early termination by the user because the user already observed desired code during the middle of the process. Especially, if you want to go with the class CodeGenerator, it is highly recommended to save the code in each iteration to improve stability.

6. Please let me know if you have any other suggestions or questions

**Comment by Juno-T** [comment]
Hi! Thank you for your time for responding with your concerns.

Before I address your concerns, I think the proposed change can handle all of the potential problems you have pointed out.
Also, I made some connection with RL simply because of the design similarity. The proposed structure was not designed for doing RL although it allows developers and researchers to easily integrate different code generation algorithms, e.g. _repair tree_ where LLM will be called many times with the same prompt and test out every generated codes.

I will address each of your concerns below.

### concern 1
> * functions meta_python.read(), meta_python.write(), and meta_python.compile() would have to return more arguments.
> * functions in meta_python will have more arguments, which would make the most complicated parts in mg_core.py and code_management.py even more complicated. For example, it will make line 113 to line 120 in mg_core.py even longer.
> * ... So I would like to make mg_core.py and code_management.py in the main branch to be as simple as possible...

The function `MetaLLM-GPT.read_run_and_test_previous_code` will be transfered to a method inside the `CodeExecutor`. It will take only 1 argument which is the parsed `code_str`. After the execution or error handling, it will just return 1 item of type `CodeBlob` containing all the information needed for constructing the next prompt.

``` python
class CodeExecutor:
    ...
    def execute(self, code_str):
        # code_str could alternatively be the path to generated code file
        # compile here
        # call `overtime_kill()` here
        # handle exception and timeout here
        code_blob = CodeBlob(code_str=code_str, exception, runtime, is_killed, ...) # store the execution output here
        return code_blob
```

Now in `MetaLLM-GPT.run()`'s while loop, you can just call `new_code_blob = self.executor.execute(code_str)`. And everything related to the execution (`stdout`, `tb`, `error`, ...) will be accessible from the code_blob returned, instead of storing them as `MetaLLM-GPT` instance's properties.
This makes `MetaLLM-GPT` more organized and less complicated, since you don't need to remember all the properties, they are all declared in `CodeBlob`.

### concern 2
> * Nonetheless, I will try if I can make a readable and writable object like this without overcomplicating mg_core.py or code_managment.py

Would you mind clarify what you meant by readable/writable object?

### concern 3
> 4\. About the code generator module: It is not recommended to simplify the class MetaLLM_GPT into the class CodeGenerator. Because:
> 
> * The application itself, aka, the meta-program, is subject to exceptions. For example, it can happen due to occasional internet disconnection or bad responses from the LLM (e.g., the generated code is too short, the code takes too long to run or the code cannot finish at all (which happens quite often), the code cannot be retrieved by GPT_turbo.extract_code_from_GPT_turbo() in inquiry.py ). Although it might be possible to configure the application to reach a relatively decent success rate, it is almost impossible to achieve a 100% success rate. Also, such a design would make the code repo generalize poorly. Because a design that is suitable for GPT might "overfit" GPT and is less successful for other LLMs.
> ...

I understand that the code generated from chatGPT could be buggy or even not runnable. However, as you did in your code, we can handle those cases. My proposal is to just move those code execution and error handling into `CodeExecutor` class and use `CodeBlob` object as a common interface. This only make it more organized and easily used by `Prompter` module. See example code in __concern 1__ for clearer detail.

The name `CodeGenerator` is may be not desired. It basically do the same thing as `MetaLLM_GPT`, so I'm not against using the same name.

### concern 4
> * I might move the function MetaLLM-GPT.inquiry_GPT into another class, which could possibly make the code simpler.

I think you meant `MetaLLM-GPT.choose_inquiry()`? I support this action. I named that class `Prompter` in my proposal. However, I think `Prompter` should return only the prompt string, not the chatGPT's response. This leaves the LLM calling to `MetaLLM-GPT` making it easy to change the LLM model if the user want to use a different one. `Prompter` will only create prompt string from previous execution result, namely `CodeBlob`, that contains stdout, error, tb, etc.

### concern 5

> * It can be very difficult to achieve all types of meta-programming features with just the following two lines:
> 
> ```
>             code_str = parse_code(response)
>             new_code_blob = self.executor(code_str)
> ```

I think these two lines are very simple and make `MetaLLM-GPT` class more organized. I think it is achievable with the right abstraction as proposed in the original post. With the code in __concern 1__, it will look exactly like this:
``` python
code_str = parse_code(response)
new_code_blob = self.executor.execute(code_str)
```

### concern 6
> 5\. I store the generated code into a file in each iteration because the meta program itself might not be able to finish due to some reasons, such as an internet disconnection or an early termination by the user because the user already observed desired code during the middle of the process. Especially, if you want to go with the class CodeGenerator, it is highly recommended to save the code in each iteration to improve stability.

I see what you mean. I think the internal execution can all be done using just memory. The 'saving into file' could just be for logging purpose. We can have an option whether you want to log the code into files or not. Of course it can be ON by default.



___
My goal here is to make it easier to use different generation algorithm, like repair tree or new prompts or using local LLM, without changing the original functionality.

If you have more concerns or disagree with any of my points, please feel free to respond.
Alternatively, I'm also open for discussing in person and/or make some demo code.

**Comment by JLX0** [comment]
Dear Juno

Thanks for the reply! I might understand your proposal. As you suggested, I will be very excited to combine MetaLLM-GPT with other algorithms! I think your requested features should be added by adding some codes to the existing codes, instead of reorganizing the existing codes.

1. To make the class CodeExecutor, you can achieve this by directly adding several lines to the existing codes. For example, you can add the following function to the class meta_python:

```

    def read_from_memory(self, code_str):
        self.combined_raw_code = code_str

```

and changing the function MetaLLM_GPT.read_run_and_test_previous_code() to the following one:
```
    def read_run_and_test_previous_code_in_memory(self,code_str):
        self.meta_instance.read_from_memory(code_str)
        
        self.meta_instance.compile()
        self.combined_raw_code = self.meta_instance.combined_raw_code

        if self.Output is not None:
            output_required = True
        else:
            output_required = False

        self.execution_killed, shared_variables = overtime_kill(self.meta_instance.execute_and_test,
                                                                target_function_args=(output_required, True, 2000,
                                                                self.Privilege,), time_limit=self.Time_limit)
        if not self.execution_killed:
            self.stdout = shared_variables["stdout"]
            self.error = shared_variables["error"]
            self.tb = shared_variables["tb"]
            self.debug_required = shared_variables["buggy"]

    return any_stuff_you_want (e.g.,  self.stdout,  self.error,  self.tb,  self.execution_killed, code_str,.... (you can also make a version without the self))
```

If you want to create such an object, please create a pull request to create a new branch. As these features are for development purposes. 

2. I believe to achieve the features you mentioned, more objects might be needed. I might add them later on (in a different branch), especially once the exact requirements for the objects become clear.

3. The class CodeGenerator is still not realistic for this application. Please double-check the 4th item in my previous reply. I do not mean that "the code generated from chatGPT could be buggy or even not runnable". I mean "The application itself, aka, **the meta-program**, is subject to exceptions". For example, exceptions can happen in the following cases: 

-  for the line "response = openai.ChatCompletion.create(model, prompt)", an internet disconnection, LLM overload, usage rate limit, or an inquiry frequency that exceeds the restriction.
- for the line " code_str = parse_code(response)",  bad responses from the LLM can lead to a lot of exceptions **for the meta program instead of the target program**.  For example, the code cannot be retrieved by GPT_turbo.extract_code_from_GPT_turbo() in inquiry.py, or the meta_python.compile() function fails.
- other situations not described in the class. For example, the generated code is too short or the code takes too long to run or the code cannot finish at all (which happens quite often)

If the exceptions occur, the following overly simplistic loop breaks:
```
while max_iteration:
    ...
    max_iteration -= 1
```

The current design in the class MetaLLM_GPT is resistant to such situations, does not count iterations in which exceptions in the meta program happen as an effective iteration, and captures and displays the types of exceptions. 

One might be able to create a simplified class based on top of MetaLLM_GPT. But again, it is adding codes to the existing codes, instead of a reorganization.

4. For a readable-only object I mean, for example, the class variables in the class CodeBlob can be printed and read. However, assigning new values to the variables in the class might not be meaningful, because the class is like a logger and the values in the variables of the class are not actually read by functions in the class meta_python. 

5. For concern 4, I mean MetaLLM-GPT.inquiry_GPT(). I pointed it out because it is a possible way to shorten the class MetaLLM_GPT

6. For concern 6, I think that could be a very good feature. Also, I think you can achieve this by adding codes to the existing codes, instead of reorganizing the codes. Please create a pull request for such a feature too. I could also do this myself in the future.

7. Let me know if you have any other suggestions or questions!

**Comment by Juno-T** [comment]
Thank you for your detailed response.
I think I understand you now. What I meant by reorganizing/restructuring was to separate or move your codes that do similar thing into a more organized abstractions, which also means adding more code as you mentioned. And this action won't remove any of your code's functionalities (resistance to chatGPT response variations, program execution errors, etc.)

And there are some over simplified proposal like `response = openai.ChatCompletion.create(model, prompt)` and `code_str = parse_code(response)`. These two lines are somethings that would make it cleaner and easier to develop upon. This is more of a feature request, rather than reorganization, to handle all those possible problems (internet connection problem, code parsing problem, etc.). Some of them are already handled in your code, but again as you mentioned, more code will be added to fulfill this feature.

As you suggested, I'll try making a fork/branch to test things out when I have time.
If you don't have anything else to add, you can close the issue. Thank you again!

**Comment by JLX0** [comment]
Understood. Please let me know if you encounter any other issues! Thanks!
